shared/urls.js

fix #408 qq sports video
x-forward 還是不行，搞錯了

fix #408 qq sports video

---

shared/urls.js

Update rules for the iqiyi PC client

---

shared/urls.js

Problem url: http://www.iqiyi.com/zongyi/wmjhlzb.html

Fix a problem for iqiyi live

---

shared/urls.js

problem video address: http://www.letv.com/ptv/vplay/23635334.html
reporting source: https://groups.google.com/forum/#!topic/unblock-youku/XEDWT3HQCPU

fix letv problem (urgent!!)

---

shared/urls.js

url not tested. plz check before merging.

Add support for tecent comics

---

shared/urls.js

因为我没有开通收费会员，所以不知道这一个URL对需要收费下载的歌有没有用。

fix for ios qq music 試聽, issue #536

---

_locales/en/messages.json
_locales/zh_CN/messages.json
_locales/zh_TW/messages.json
chrome/pages/js/popup.js
chrome/pages/popup.html

added faq link in chrome extention page

---

_locales/en/messages.json
_locales/zh_CN/messages.json
_locales/zh_TW/messages.json
chrome/pages/js/popup.js

之前abbr tag的mouse over要好几秒才出来，体验不是很好，改用了Bootstrap的Tooltips，可以很快的显示扩展内容，也方便以后对Tooltips的样式进行修改

Add tooltip to abbr tag for better experience

---

shared/urls.js

https://groups.google.com/forum/#!topic/unblock-youku/Dgicjj1L6Gg

Fix Google Group report 騰訊漫畫網can not unlock

---

package.json

I briefly reviewed the change log for `validator`. I understand this project isn't using any of the new functions yet, but it's still good to sync up its dependencies.
For the `eslint` modules, this upgrade doesn't break any of the unit tests, so I assume this would cover it. However, please double check before merging. I don't want to break Unblock-Youku because of this update. Thanks!

Update npm package dependencies

---

_locales/en/messages.json
_locales/zh_CN/messages.json
_locales/zh_TW/messages.json
chrome/config.js
chrome/header.js
chrome/pages/js/popup.js
chrome/pages/popup.html

请简要描述此 Pull Request 的内容（例如，使用 xxx 办法解决 Issue #yyy）:
Chrome extension add a Off mode for #339 
There are total four mode now, Off, Lite, Normal, Redirect
Chrome management API does not has good solution for disable
- Preserve storage_monitor, get_storage, setup_mode_settings logic in Off mode in config.js
- Move setup_extra_header()

add Off mode

---

shared/urls.js

small fix on bilibili

---

shared/urls.js

This is the rules for restrictions of LETV boxes

Fix letv TV boxes problems

---

shared/urls.js

Change Xunlei Kankan to kankan.com

---

manifest.json
shared/tools.js

请简要描述此 Pull Request 的内容（例如，使用 xxx 办法解决 Issue #yyy）:
Pretty printing JSON format and correcting typos in comments. Should not change any behaviours of the extension.

Correcting a few nits in the code

---

shared/urls.js

Just a test. Cancel it if it's not okay.

test for Netease music

---

shared/urls.js

Fix qq music new web version

---

shared/urls.js

刚刚测试了一下发现新的规则歌单还是变灰，经过和DNS的对比发现少了一条规则（就是之前被删的那条），现在补上。

small fix to qq music

---

shared/urls.js

请简要描述此 Pull Request 的内容（例如，使用 xxx 办法解决 Issue #yyy）:
fix for following youku problem
https://bbs.uku.im/t/topic/140
https://bbs.uku.im/t/topic/141
https://bbs.uku.im/t/topic/142
https://bbs.uku.im/t/topic/144

Fix for youku problem reported in http://bbs.uku.im/

---

shared/urls.js

fix the problem of QQ pay

---

shared/urls.js

Fix kuwo music app

---

shared/urls.js

Add the rule of https according to the change of https webpage of Tecent.

Fix Tecent Video https

---

shared/urls.js

Fix QQ music VIP in https

---

shared/urls.js

Related issue is reported in #725

Fix QQ music https

---

shared/urls.js

https://bbs.uku.im/t/topic/449
For Letv iOS apps.

Additional link for Tommy's Letv pull request

---

shared/urls.js

Move player-pc.le.com/mms/out/video/ to proper location for letv problem report here
https://bbs.uku.im/t/topic/484/2
请简要描述此 Pull Request 的内容（例如，使用 xxx 办法解决 Issue #yyy）:

Fix Letv problem

---

shared/urls.js

Fix issue report here https://bbs.uku.im/t/ios10-dns-qq/554
and
Kuwo music

Fix iOS QQ music app and kuwo music

---

shared/urls.js

fix problem reported here https://bbs.uku.im/t/topic/566

fix kugou music web

---

manifest.json
shared/urls.js

fix topic 1997

---

manifest.json
shared/urls.js

Fix QQ music
